language: go

go:
  - 1.20

env:
  - GO111MODULE=on

script:
  - go mod tidy
  - diff -u <(echo -n) <(gofmt -d .)
  - go test -v -race -coverprofile=coverage.txt -covermode=atomic ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)